import { Template, CleaningStep } from './types';

function makeStep(id: number, action: CleaningStep['action'], desc: string, column?: string, params?: Record<string, any>): CleaningStep {
  return { id: `tpl-step-${id}`, action, column, params, description: desc, enabled: true };
}

export const builtInTemplates: Template[] = [
  {
    id: 'tpl-1',
    name: 'Customer Master Data Cleanup',
    description: 'Clean CRM exports: remove duplicates, validate emails/phones, fix name capitalization, fill missing values.',
    category: 'Customer/CRM',
    icon: '👥',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove completely empty rows'),
      makeStep(2, 'remove_duplicates', 'Remove duplicate customers by Email', 'Email'),
      makeStep(3, 'validate_email', 'Validate & fix email format', 'Email'),
      makeStep(4, 'validate_phone', 'Format phone numbers', 'Phone'),
      makeStep(5, 'text_transform', 'Fix name capitalization', 'Name', { transformation: 'title_case' }),
      makeStep(6, 'fill_missing', 'Fill missing Country', 'Country', { method: 'constant', value: 'Unknown' }),
      makeStep(7, 'remove_whitespace', 'Remove extra whitespace', 'Name'),
    ],
    tags: ['CRM', 'customer', 'validation', 'dedup'],
    usageCount: 1243,
    rating: 4.8,
    isPremium: false,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-01-15',
  },
  {
    id: 'tpl-2',
    name: 'Email Marketing List Cleaner',
    description: 'Clean email subscriber lists: remove invalid formats, fix typos, lowercase standardization, remove duplicates.',
    category: 'Marketing',
    icon: '📧',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove empty rows'),
      makeStep(2, 'validate_email', 'Validate & fix email typos', 'Email'),
      makeStep(3, 'text_transform', 'Lowercase all emails', 'Email', { transformation: 'lowercase' }),
      makeStep(4, 'remove_duplicates', 'Remove duplicate emails', 'Email'),
      makeStep(5, 'remove_whitespace', 'Trim whitespace', 'Email'),
      makeStep(6, 'text_transform', 'Standardize names', 'Name', { transformation: 'title_case' }),
    ],
    tags: ['email', 'marketing', 'newsletter', 'hygiene'],
    usageCount: 890,
    rating: 4.7,
    isPremium: false,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-01-20',
  },
  {
    id: 'tpl-3',
    name: 'Sales Pipeline Standardization',
    description: 'Clean Salesforce/HubSpot exports: standardize stages, validate amounts, fill missing dates.',
    category: 'Sales',
    icon: '💰',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove empty rows'),
      makeStep(2, 'text_transform', 'Standardize Deal Stage', 'Stage', { transformation: 'title_case' }),
      makeStep(3, 'number_format', 'Clean Deal Amount', 'Amount'),
      makeStep(4, 'fill_missing', 'Fill missing Close Date', 'Close_Date', { method: 'constant', value: 'TBD' }),
      makeStep(5, 'standardize_date', 'Standardize dates', 'Created_Date'),
      makeStep(6, 'remove_duplicates', 'Remove duplicate deals', 'Deal_Name'),
    ],
    tags: ['sales', 'pipeline', 'CRM', 'deals'],
    usageCount: 654,
    rating: 4.6,
    isPremium: false,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-02-01',
  },
  {
    id: 'tpl-4',
    name: 'E-commerce Order Processing',
    description: 'Clean order data: standardize statuses, validate dates, format addresses, remove test orders.',
    category: 'E-commerce',
    icon: '🛒',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove empty rows'),
      makeStep(2, 'text_transform', 'Standardize Order Status', 'Status', { transformation: 'title_case' }),
      makeStep(3, 'standardize_date', 'Standardize Order Date', 'Order_Date'),
      makeStep(4, 'number_format', 'Clean Total Amount', 'Total'),
      makeStep(5, 'text_transform', 'Standardize State codes', 'State', { transformation: 'uppercase' }),
      makeStep(6, 'remove_duplicates', 'Remove duplicate orders', 'Order_ID'),
      makeStep(7, 'fill_missing', 'Fill missing Shipping', 'Shipping', { method: 'constant', value: '0' }),
    ],
    tags: ['ecommerce', 'orders', 'retail'],
    usageCount: 432,
    rating: 4.5,
    isPremium: false,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-02-10',
  },
  {
    id: 'tpl-5',
    name: 'HR Employee Data Cleanup',
    description: 'Clean HRIS exports: standardize departments, validate dates, fix job titles, fill missing managers.',
    category: 'HR/People',
    icon: '🏢',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove empty rows'),
      makeStep(2, 'remove_duplicates', 'Remove duplicate employees', 'Employee_ID'),
      makeStep(3, 'text_transform', 'Standardize Department', 'Department', { transformation: 'title_case' }),
      makeStep(4, 'text_transform', 'Fix job titles', 'Job_Title', { transformation: 'title_case' }),
      makeStep(5, 'standardize_date', 'Standardize Hire Date', 'Hire_Date'),
      makeStep(6, 'fill_missing', 'Fill missing Manager', 'Manager', { method: 'constant', value: 'CEO' }),
      makeStep(7, 'validate_email', 'Validate work email', 'Email'),
    ],
    tags: ['HR', 'employee', 'HRIS', 'people'],
    usageCount: 321,
    rating: 4.4,
    isPremium: false,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-02-15',
  },
  {
    id: 'tpl-6',
    name: 'Bank Statement Reconciliation',
    description: 'Clean bank exports: standardize dates, clean amounts, remove summary rows, flag large transactions.',
    category: 'Finance',
    icon: '🏦',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove summary/empty rows'),
      makeStep(2, 'standardize_date', 'Standardize Transaction Date', 'Date'),
      makeStep(3, 'number_format', 'Clean Amount values', 'Amount'),
      makeStep(4, 'remove_whitespace', 'Clean Description', 'Description'),
      makeStep(5, 'remove_duplicates', 'Remove duplicate transactions', 'Reference'),
      makeStep(6, 'text_transform', 'Standardize Category', 'Category', { transformation: 'title_case' }),
    ],
    tags: ['finance', 'banking', 'reconciliation', 'accounting'],
    usageCount: 567,
    rating: 4.7,
    isPremium: true,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-03-01',
  },
  {
    id: 'tpl-7',
    name: 'Product Catalog Cleaner',
    description: 'Clean Shopify/WooCommerce exports: standardize SKUs, validate prices, fill missing categories.',
    category: 'E-commerce',
    icon: '📦',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove empty rows'),
      makeStep(2, 'text_transform', 'Standardize SKU format', 'SKU', { transformation: 'uppercase' }),
      makeStep(3, 'number_format', 'Clean Price values', 'Price'),
      makeStep(4, 'fill_missing', 'Fill missing Category', 'Category', { method: 'constant', value: 'Uncategorized' }),
      makeStep(5, 'remove_duplicates', 'Remove duplicate SKUs', 'SKU'),
      makeStep(6, 'remove_whitespace', 'Clean Product Name', 'Product_Name'),
      makeStep(7, 'text_transform', 'Title Case Product Names', 'Product_Name', { transformation: 'title_case' }),
    ],
    tags: ['products', 'catalog', 'shopify', 'ecommerce'],
    usageCount: 445,
    rating: 4.5,
    isPremium: true,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-03-10',
  },
  {
    id: 'tpl-8',
    name: 'Survey Response Cleaning',
    description: 'Clean survey exports: remove incomplete responses, standardize answers, flag suspicious patterns.',
    category: 'Marketing',
    icon: '📊',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove empty responses'),
      makeStep(2, 'remove_whitespace', 'Clean Response text', 'Response'),
      makeStep(3, 'text_transform', 'Standardize answers', 'Answer', { transformation: 'title_case' }),
      makeStep(4, 'remove_duplicates', 'Remove duplicate submissions', 'Respondent_ID'),
      makeStep(5, 'fill_missing', 'Fill missing fields', 'Category', { method: 'constant', value: 'Not Specified' }),
      makeStep(6, 'standardize_date', 'Standardize submission date', 'Submitted_At'),
    ],
    tags: ['survey', 'research', 'feedback', 'NPS'],
    usageCount: 234,
    rating: 4.3,
    isPremium: true,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-03-15',
  },
  {
    id: 'tpl-9',
    name: 'Lead Scoring Data Prep',
    description: 'Prepare marketing leads: validate business emails, standardize job titles, remove incomplete leads.',
    category: 'Marketing',
    icon: '🎯',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove incomplete leads'),
      makeStep(2, 'validate_email', 'Validate lead emails', 'Email'),
      makeStep(3, 'text_transform', 'Standardize Job Title', 'Job_Title', { transformation: 'title_case' }),
      makeStep(4, 'fill_missing', 'Fill missing Industry', 'Industry', { method: 'constant', value: 'Not Specified' }),
      makeStep(5, 'text_transform', 'Uppercase Lead Source', 'Lead_Source', { transformation: 'uppercase' }),
      makeStep(6, 'remove_duplicates', 'Remove duplicate leads', 'Email'),
      makeStep(7, 'validate_phone', 'Validate phone numbers', 'Phone'),
    ],
    tags: ['leads', 'marketing', 'scoring', 'automation'],
    usageCount: 378,
    rating: 4.6,
    isPremium: true,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-04-01',
  },
  {
    id: 'tpl-10',
    name: 'Invoice Data Standardization',
    description: 'Clean invoice data: standardize numbers, validate dates, fill payment terms, remove cancelled items.',
    category: 'Finance',
    icon: '🧾',
    steps: [
      makeStep(1, 'remove_empty_rows', 'Remove empty rows'),
      makeStep(2, 'remove_special_chars', 'Clean Invoice Number', 'Invoice_Number'),
      makeStep(3, 'standardize_date', 'Standardize Invoice Date', 'Invoice_Date'),
      makeStep(4, 'standardize_date', 'Standardize Due Date', 'Due_Date'),
      makeStep(5, 'number_format', 'Clean Amount', 'Amount'),
      makeStep(6, 'fill_missing', 'Fill Payment Terms', 'Payment_Terms', { method: 'constant', value: 'Net 30' }),
      makeStep(7, 'remove_duplicates', 'Remove duplicate invoices', 'Invoice_Number'),
    ],
    tags: ['invoice', 'finance', 'accounting', 'AP'],
    usageCount: 298,
    rating: 4.4,
    isPremium: true,
    isPublic: true,
    createdBy: 'DataSpark Team',
    createdAt: '2025-04-10',
  },
];

export const templateCategories = [
  { name: 'All', icon: '📋', count: builtInTemplates.length },
  { name: 'Customer/CRM', icon: '👥', count: builtInTemplates.filter(t => t.category === 'Customer/CRM').length },
  { name: 'Marketing', icon: '📧', count: builtInTemplates.filter(t => t.category === 'Marketing').length },
  { name: 'Sales', icon: '💰', count: builtInTemplates.filter(t => t.category === 'Sales').length },
  { name: 'Finance', icon: '🏦', count: builtInTemplates.filter(t => t.category === 'Finance').length },
  { name: 'E-commerce', icon: '🛒', count: builtInTemplates.filter(t => t.category === 'E-commerce').length },
  { name: 'HR/People', icon: '🏢', count: builtInTemplates.filter(t => t.category === 'HR/People').length },
];
